spring.datasource.url=jdbc:mysql://avnadmin:AVNS_nxQK_epmPKR95MiQ2iX@mysql-dbatt-sivaranjanidec2005-bf15.e.aivencloud.com:23867/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_nxQK_epmPKR95MiQ2iX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=23867


jwt.secret=mySuperSecretKeyForAttendanceSystem2026JwtToken

jwt.expiration=86400000s

#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sivaranjanix6@gmail.com
spring.mail.password=josw scxj hqfl pyzk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true